### ISSUE TITLE
我使用你的device编译lineageos16时候,得到下面的错误,请问怎么解决呢?拜托了

### ISSUE THREAD

**Issue by Ni1994** [GuaiYiHu/android_device_xiaomi_clover-oss#5]
[571/950] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
system/sepolicy/Android.mk:89: warning: Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.
[950/950] including vendor/xiaomi/clover/Android.mk ...
external/wpa_supplicant_8/hostapd/Android.mk: error: hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-qcom (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm64) missing libcld80211 (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-qcom (STATIC_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm) missing libcld80211 (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/audio-caf/msm8998/hal/Android.mk: error: audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing libtinycompress_vendor (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/audio-caf/msm8998/hal/Android.mk: error: audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing libtinycompress_vendor (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:837: error: exiting from previous errors.
04:17:47 ckati failed with: exit status 1

**Comment by ValentinLiu15** [comment]
你好，我也遇到了这个问题，请问您是怎么解决的呢，能不能告诉我呢
